function(add_thread_sanitizer target)
    if(NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Build type" FORCE)
    endif()

    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
            target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            message(WARNING "Thread Sanitizer is not supported on MSVC.")
        else()
            message(WARNING "Unknown compiler: Thread Sanitizer may not be supported.")
        endif()
    else()
        message(WARNING "Thread Sanitizer is typically used in Debug builds. Current build type: ${CMAKE_BUILD_TYPE}")
    endif()
endfunction()
